"""Added movie

Revision ID: bed4e7b11a3f
Revises: 9a629313574f
Create Date: 2023-08-02 13:59:00.690084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bed4e7b11a3f'
down_revision = '9a629313574f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Movie_description'), 'Movie', ['description'], unique=False)
    op.create_index(op.f('ix_Movie_id'), 'Movie', ['id'], unique=False)
    op.create_index(op.f('ix_Movie_original_language'), 'Movie', ['original_language'], unique=False)
    op.create_index(op.f('ix_Movie_poster_path'), 'Movie', ['poster_path'], unique=False)
    op.create_index(op.f('ix_Movie_title'), 'Movie', ['title'], unique=False)
    op.drop_index('ix_task_description', table_name='task')
    op.drop_index('ix_task_id', table_name='task')
    op.drop_index('ix_task_title', table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='task_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.create_index('ix_task_title', 'task', ['title'], unique=False)
    op.create_index('ix_task_id', 'task', ['id'], unique=False)
    op.create_index('ix_task_description', 'task', ['description'], unique=False)
    op.drop_index(op.f('ix_Movie_title'), table_name='Movie')
    op.drop_index(op.f('ix_Movie_poster_path'), table_name='Movie')
    op.drop_index(op.f('ix_Movie_original_language'), table_name='Movie')
    op.drop_index(op.f('ix_Movie_id'), table_name='Movie')
    op.drop_index(op.f('ix_Movie_description'), table_name='Movie')
    op.drop_table('Movie')
    # ### end Alembic commands ###
