"""Added your_score

Revision ID: d884f6142b73
Revises: bed4e7b11a3f
Create Date: 2023-08-03 11:12:04.600384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd884f6142b73'
down_revision = 'bed4e7b11a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movie', sa.Column('your_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movie', 'your_score')
    # ### end Alembic commands ###
