"""Added tablename

Revision ID: e11b65762e40
Revises: d884f6142b73
Create Date: 2023-08-03 11:13:49.602374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e11b65762e40'
down_revision = 'd884f6142b73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('your_score', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_description'), 'movie', ['description'], unique=False)
    op.create_index(op.f('ix_movie_id'), 'movie', ['id'], unique=False)
    op.create_index(op.f('ix_movie_original_language'), 'movie', ['original_language'], unique=False)
    op.create_index(op.f('ix_movie_poster_path'), 'movie', ['poster_path'], unique=False)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.drop_index('ix_Movie_description', table_name='Movie')
    op.drop_index('ix_Movie_id', table_name='Movie')
    op.drop_index('ix_Movie_original_language', table_name='Movie')
    op.drop_index('ix_Movie_poster_path', table_name='Movie')
    op.drop_index('ix_Movie_title', table_name='Movie')
    op.drop_table('Movie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Movie_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('original_language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poster_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('watched', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('your_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='Movie_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Movie_pkey')
    )
    op.create_index('ix_Movie_title', 'Movie', ['title'], unique=False)
    op.create_index('ix_Movie_poster_path', 'Movie', ['poster_path'], unique=False)
    op.create_index('ix_Movie_original_language', 'Movie', ['original_language'], unique=False)
    op.create_index('ix_Movie_id', 'Movie', ['id'], unique=False)
    op.create_index('ix_Movie_description', 'Movie', ['description'], unique=False)
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_poster_path'), table_name='movie')
    op.drop_index(op.f('ix_movie_original_language'), table_name='movie')
    op.drop_index(op.f('ix_movie_id'), table_name='movie')
    op.drop_index(op.f('ix_movie_description'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
